wechat_official_account_config:
  oauth:
    app_id: "your_wechat_app_id"
    app_secret: "your_wechat_app_secret"
  base_uri: "https://api.weixin.qq.com"
  proxy_uri: ""
  timeout: 5.0
  http_debug: true
  component_app_id: "your_component_app_id"
  component_app_token: "your_component_app_token"

byte_dance_douyin_config:
  base_uri: "https://open.douyin.com"
  proxy_uri: ""
  http_debug: false
  timeout: 5.0
  oauth:
    app_id: "your_douyin_app_id"
    app_secret: "your_douyin_app_secret"

redbook_juguang_config:
  base_uri: "https://www.xiaohongshu.com"
  proxy_uri: ""
  timeout: 5.0
  http_debug: false
  oauth:
    app_id: "your_redbook_app_id"
    app_secret: "your_redbook_app_secret"

